# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-08 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('ram', models.CharField(max_length=4)),
                ('battery', models.CharField(max_length=10)),
                ('screen_size', models.FloatField()),
                ('description', models.TextField()),
                ('cover', models.URLField()),
            ],
        ),
    ]
